apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'app-staging'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Staging'
          - name: 'PROJECT_ID'
            value: 'PROJECT_ID'
          - name: 'GPG_SECRET_ID'
            value: 'gpgkey'
          - name: 'PASPPHRASE_SECRET_ID'
            value: 'Passphrase'
          - name: 'DESTINATION_BUCKET'
            value: 'gpg_buckets_abhi' 
