apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: 'app-prod'
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: '1'
    spec:
      containers:
      - name: 'app'
        image: 'app'
        env:
          - name: 'TARGET'
            value: 'Prod'
          - name: 'PROJECT_ID'
            value: '${PROJECT_ID}'
          - name: 'GPG_SECRET_ID'
            value: '${GPG_SECRET_ID}'
          - name: 'PASPPHRASE_SECRET_ID'
            value: '${PASPPHRASE_SECRET_ID}'
          - name: 'DESTINATION_BUCKET'
            value: '${DESTINATION_BUCKET}'
