name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "final" ]

env:
  PROJECT_ID: "abhishek-anand-dev" # TODO: update Google Cloud project id
  GAR_LOCATION: "us-central1" # TODO: update Artifact Registry location
  SERVICE: "gpg-decryption" # TODO: update Cloud Run service name
  REGION: "us-central1" # TODO: update Cloud Run service region
  IMAGE: "gpg"
  GPG_SECRET_ID: "gpgkey" # TODO: update your environment variables
  PASPPHRASE_SECRET_ID: "Passphrase"

jobs:
  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Authenticate with Google Cloud
      - name: Google Auth
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      # Build and push Docker image using Cloud Build
      - name: Cloud Build
        run: |-
          gcloud builds submit --tag "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.IMAGE}}:${{ github.sha }}" .

      # Deploy to Cloud Run with environment variables
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v0
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          image: "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
          env_vars: |
            PROJECT_ID=${{ env.PROJECT_ID }}
            GPG_SECRET_ID=${{ env.GPG_SECRET_ID }}
            PASPPHRASE_SECRET_ID=${{ env.PASPPHRASE_SECRET_ID }}
